### ISSUE TITLE
Assets/BrowserView.cs(102,44): error CS1644: Feature `out variable declaration' cannot be used because it is not part of the C# 6.0 language specification

### ISSUE THREAD

**Issue by elblogbruno** [IanPhilips/UnityAndroidVRBrowser#4]
Great job overall!
Keep continue like that!
I've got this error maybe you can help.

Assets/BrowserView.cs(102,44): error CS1644: Feature `out variable declaration' cannot be used because it is not part of the C# 6.0 language specification

Thanks!

**Comment by IanPhilips** [comment]
I think that may depend on your scripting runtime version or api compatibility level, both of those are in the Player>Settings>Other Settings. If you want to keep your c# version you can just declare the out variable a line prior, so instead of:
` if (ValidHttpURL(potentialUrl, out var outUri))`
change it to:
`var outUri;`
`if (ValidHttpURL(potentialUrl, out outUri))`

**Comment by elblogbruno** [comment]
Ok cool i'll give It a try and tell you!
Thanks!
I'll send you Photos of the project i'm working on when i put your software in!
Thanks a lot!

--
Enviado desde la aplicación myMail para Android

jueves, 06 diciembre 2018, 10:40p. m. +01:00 de Ian Philips notifications@github.com<mailto:notifications@github.com>:


I think that may depend on your scripting runtime version or api compatibility level, both of those are in the Player>Settings>Other Settings. If you want to keep your c# version you can just declare the out variable a line prior, so instead of:
if (ValidHttpURL(potentialUrl, out var outUri))
change it to:
var outUri;
if (ValidHttpURL(potentialUrl, out outUri))

**Comment by elblogbruno** [comment]
I got it working perfectly! Just changed 👍 
var outUri;
if (ValidHttpURL(potentialUrl, out outUri))

to 

Uri outUri;
if (ValidHttpURL(potentialUrl, out outUri))
